# Generated by Django 4.2.5 on 2023-10-21 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='recommended',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='watched',
        ),
    ]
