# Generated by Django 4.2.5 on 2023-10-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_recommended_remove_movie_watched'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
